### ISSUE TITLE
Weird color palette for the blocks

### ISSUE THREAD

**Issue by Fabccc** [TABmk/minecraft-blocks-render#11]
Result
![image](https://user-images.githubusercontent.com/33267330/188887708-c4359eac-ea79-4c16-8e5c-ec9a976b2e2e.png)
Excepted
![image](https://user-images.githubusercontent.com/33267330/188888946-6f11a677-24e8-490e-875c-9061cd5cd717.png)

Steps to reproduce
```shell
cp ~/.minecraft/versions/1.19.2/1.19.2.jar .
mbr grab -f 1.19.2.jar -d 
mbr render -t base -r 32 -s 10 -d
```
Maybe i didn't use a correct configuration. I'm really willing to help if it's a bug !

**Comment by TABmk** [comment]
@ComminQ Hi, you're using color-reducer option (-r), just remove it or set 1

try `mbr render -t png -s 10`
